

# to be used in RStudio "new project" GUI
new_project <- function(path, ...) {
  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # generate header for file
  header <- c(
    "# This file was generated by a call to 'shinyspring::new_project()'.",
    "# The following inputs were received:",
    "default: ",
    ""
  )

  #pick up template
  config_template <- load_config_template()

  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  text <- apply_project_params_to_template(dots , config_template)

  # collect into single text string
  contents <- paste(
   # paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "config.yml"))
}
